<?php

//  EN-Revision: 5269

$labels['basic'] = '新しいメッセージの通知をブラウザーに表示する';
$labels['desktop'] = '新しいメッセージの通知をデスクトップに表示する';
$labels['sound'] = '新しいメッセージが届くと音を再生する';
$labels['test'] = 'テスト';
$labels['title'] = '新しいメールです!';
$labels['body'] = '新しいメッセージを受信しました。';
$labels['testbody'] = 'これはテスト通知です。';
$labels['desktopdisabled'] = 'ブラウザーでデスクトップ通知が無効になっています。';
$labels['desktopunsupported'] = 'ブラウザーがデスクトップ通知をサポートしていません。';

?>
