<?php

/*
 +-----------------------------------------------------------------------+
 | language/#lang/labels.inc                                             |
 |                                                                       |
 | Language file of the RoundCube Webmail client                         |
 | Copyright (C) 2008-2010, RoundCube Dev. - Switzerland                 |
 | Licensed under the GNU GPL                                            |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author:                                                               |
 +-----------------------------------------------------------------------+

*/

$labels = array();
